artifact_location: /mnt/All_Needs/Development/Data-Science/ovoscan-pipeline/runs/mlflow/112053531178586064
creation_time: 1768506110132
experiment_id: '112053531178586064'
last_update_time: 1768506110132
lifecycle_stage: active
name: ovoscan_train_runs
