artifact_location: /mnt/All_Needs/Development/Data-Science/ovoscan-pipeline/runs/mlflow/655204722122095933
creation_time: 1768506856606
experiment_id: '655204722122095933'
last_update_time: 1768506856606
lifecycle_stage: active
name: /mnt/All_Needs/Development/Data-Science/ovoscan-pipeline/yolo_dataset_cache/ovoscan_train_runs
