apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ovoscan.fullname" . }}-config
data:
  APP_NAME: {{ .Values.env.APP_NAME | quote }}
  APP_ENV: {{ .Values.env.APP_ENV | quote }}
  APP_LOG_LEVEL: {{ .Values.env.APP_LOG_LEVEL | quote }}
  CONFIDENCE_THRESHOLD: {{ .Values.env.CONFIDENCE_THRESHOLD | quote }}
  ENABLE_RAG: {{ .Values.env.ENABLE_RAG | quote }}
  ENABLE_METRICS: {{ .Values.env.ENABLE_METRICS | quote }}
  MLFLOW_TRACKING_URI: {{ .Values.env.MLFLOW_TRACKING_URI | quote }}
  OLLAMA_HOST: {{ .Values.env.OLLAMA_HOST | quote }}
  OLLAMA_MODEL: {{ .Values.env.OLLAMA_MODEL | quote }}