apiVersion: v1
kind: Service
metadata:
  name: {{ include "ovoscan.fullname" . }}-api-service
  labels:
    app: {{ include "ovoscan.fullname" . }}
    component: api
spec:
  selector:
    app: {{ include "ovoscan.fullname" . }}
    component: api
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: {{ .Values.service.type }}