artifact_location: /mnt/All_Needs/Development/Data-Science/ovoscan-pipeline/runs/mlflow/0
creation_time: 1768506110117
experiment_id: '0'
last_update_time: 1768506110117
lifecycle_stage: active
name: Default
